version: '3.9'

services:
  server:
    image: 'docker-spring-boot-postgres:latest'
    build:
      context: server
    container_name: server
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/compose-postgres
      - SPRING_DATASOURCE_USERNAME=compose-postgres
      - SPRING_DATASOURCE_PASSWORD=compose-postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "8080:8080"

  db:
    image: 'postgres:15-alpine'
    container_name: db
    environment:
      - POSTGRES_USER=compose-postgres
      - POSTGRES_PASSWORD=compose-postgres
    ports:
      - "6060:5432"

  simulator:
    build:
      context: simulator
      dockerfile: Dockerfile
    deploy:
      mode: replicated
      replicas: 24
